#Banco H2

app:
  message: This is the property file to the ${spring.application.name} specific for DEV environment

server:
  port: 8080
  ssl:
    enabled: true
    keyStoreType: PKCS12
    key-store: snoweeapi.p12
    key-store-password: ${env.keystore.password}

management:
  endpoints:
    endpoint-by-default: false
    web:
      exposure:
        include: 'health,prometheus'
    endpoint:
      health:
        enabled: true
        show-details: true
      prometheus:
        enabled: true
        show-details: true

spring:
  datasource:
    url: jdbc:postgresql://${env.database.hostname}:5432/dbsnowee
    driverClassName: org.postgresql.Driver
    platform: postgres
    username: postgres
    password: ${env.database.password}
  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console


env.user.admin.username: ${USER_ADMIN_USERNAME}
env.user.admin.password: ${USER_ADMIN_PASSWORD}
env.user.tester.username: ${USER_TESTER_USERNAME}
env.user.tester.password: ${USER_TESTER_PASSWORD}
env.user.guest.username: ${USER_GUEST_USERNAME}
env.user.guest.password: ${USER_GUEST_PASSWORD}