name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test surefire-report:report
    - name: Update index.html
      run: |
        mv target/surefire-reports/surefire-report.html docs/index.html
    - name: Commit and push changes
      run: |
        git config --global user.email "actions@users.noreply.github.com"
        git config --global user.name "GitHub Actions"
        git add docs/index.html
        git commit -m "Update index.html via GitHub Actions"
        git push
